# Works with https://github.com/actions/labeler/
# Below this line, the keys are labels to be applied, and the values are the file globs to match against.

advance:
  - changed-files:
      - any-glob-to-any-file: content/docs/advance/*

basic:
  - changed-files:
      - any-glob-to-any-file: content/docs/basic/*

commands:
  - changed-files:
      - any-glob-to-any-file: "content/docs/commands/*"

performance:
  - changed-files:
      - any-glob-to-any-file: content/docs/performance/*
